var width = 500;
var height = 500;
var data;

d3.csv("candy.csv", function (csv) {
	for (var i = 0; i < csv.length; ++i) {
		//csv.[i].columnAttribute = format to number or string
	}
	data = csv;
});

/*
consider referencing this code for auto-play story telling vis:
https://bl.ocks.org/officeofjane/47d2b0bfeecfcb41d2212d06d095c763

CANDY TYPES IN CVS
------------------
FULL_SIZED_CANDY_BAR
BUTTERFINGER
CANDY_CORN
CHICLETS
DOTS
FUZZY_PEACHES
GOOD_N_PLENTY
GUMMY_BEARS
HEALTHY_FRUIT
HEATH_BAR
HERSHEYS_DARK
HERSHEYS_MILK
HERSHEYS_KISSES
JOLLY_RANCHER
JUNIOR_MINTS
KITKAT
LAFFYTAFFY
LEMONHEADS
LICORICE
BLACK_LICORICE
LOLLIPOPS
MIKE_AND_IKE
MILK_DUDS
MILKYWAY
MNMS
PEANUT_MNMS
MINT_KISSES
MR_GOODBAR
NERDS
NESTLE_CRUNCH
PEEPS
PIXY_STIX
REESES_PB_CUPS
REESES_PIECES
ROLOS
SKITTLES
SNICKERS
SOURPATCH_KIDS
STARBURST
SWEDISH_FISH
TIC_TACS
THREE_MUSKETEERS
TOBLERONE
TRAIL_MIX
TWIX
WHATCHAMACALLIT_BARS
YORK_PEPPERMINT_PATTIES

*/